name: nort
description: "Secure your notes"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.17
  flutter_native_splash: ^2.4.1
  sqflite: ^2.3.3+1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  path: ^1.9.0
  crypto: ^3.0.6
  shared_preferences: ^2.3.3
  cryptography: ^2.7.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: AnekLatin
      fonts:
        - asset: assets/fonts/AnekLatin/AnekLatin-Regular.ttf
          weight: 400
        - asset: assets/fonts/AnekLatin/AnekLatin-Bold.ttf
          weight: 700
        - asset: assets/fonts/AnekLatin/AnekLatin-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AnekLatin/AnekLatin-Medium.ttf
          weight: 500

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  android: true
  ios: true
